### PR TITLE
Add Fetch Robotics

### PR DESCRIPTION
**Pull request by lucbettaieb**
Adding fetch robotics to companies.

### CODE REVIEW

**Comment by Kiloreux** [comment]
Please use a new line for your added element.

**Comment by lucbettaieb** [comment]
Weird.  Fixed that.

**Comment by lucbettaieb** [comment]
@Kiloreux merge at your leisure,  if you want me to rebase i can.

**Comment by Kiloreux** [comment]
@lucbettaieb Thank you so much.

**Pull request merged**
